image: mist/polymer-cli

before_script:
  - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - npm install

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - polymer lint
  tags:
    - docker

test:
  stage: test
  script:
    - polymer test
  tags:
    - docker