image: printminion/polymer-tester

before_script:
  - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - npm install -g npm
  - npm install -g polymer-cli
  - export PATH=$PWD/node_modules/.bin:$PATH

cache:
  paths:
  - node_modules/

stages:
  - lint
  - test

lint:
  stage: lint
  script:
   - npm install
   - xvfb-run polymer lint
  tags:
    - docker

test:
  stage: test
  script:
   - npm install
   - xvfb-run polymer test
  tags:
    - docker
