image: mist/polymer-cli

stages:
  - lint
  - test

test_job:
  stage: test
  script:
  - polymer test

lint:
  stage: lint
  script:
    - polymer lint
  tags:
    - docker

test:
  stage: test
  script:
    - polymer test
  tags:
    - docker